Fixes #27162 - Use roles_path from settings
theforeman/smart_proxy_ansible pull request #19
Opened 2019-06-27 05:53 UTC by xprazak2

2019-06-27 12:26 UTC, xprazak2 commented
I fixed the tests.

2019-06-27 14:22 UTC, ares commented
needs https://github.com/theforeman/smart_proxy_ansible/pull/19

2019-06-28 05:47 UTC, xprazak2 commented on lib/smart_proxy_ansible/roles_reader.rb
> +        def default_config_file
There is not a non-default. I just kept the same name as the constant had.

2019-06-28 07:59 UTC, xprazak2 commented
I made changes to always rely on `roles_path` that we deploy into `ansible.cfg` as suggested in changes for [installer](https://github.com/theforeman/puppet-foreman_proxy/pull/518/files#r298210501)

2019-06-28 08:15 UTC, xprazak2 commented on lib/smart_proxy_ansible/roles_reader.rb
> +        def default_config_file
Now it is renamed

2020-11-05 09:41 UTC, adamruzicka commented
Needs a rebase

2020-12-23 11:31 UTC, ezr-ondrej requested changes
Looks good, I've rebased to see the tests, but found the naming inconsistency and what about the config change? Won't the users who doesn't have the config in working dir get confusing results, because import will stop working for them?

2020-12-23 11:31 UTC, ezr-ondrej commented on lib/smart_proxy_ansible/roles_reader.rb
> +          File.join ::Proxy::Ansible::Plugin.settings.ansible_working_dir, '.ansible.cfg'
this is wrong. In the working_directory we should look for `/ansible.cfg` according to https://docs.ansible.com/ansible/latest/reference_appendices/config.html
And shouldn't we acrually implement a fallback to the default? :thinking:

The fact that working dir is by default == to home dir should not IMO matter, user can change that and get confused or we can decide to change the default in the future.
I think we should go with `<working_directory>/ansible.cfg` with fallback to `~<rex/ansible user>/.ansible.cfg` and maybe even fallback to the system config.
Do you think we can do something like that ? :thinking:

2021-03-23 16:07 UTC, ares commented
any update on this? a user asked for this recently (well they wanted to scan roles directory recursively, but having a way to set the roles path would be much better and safer)

2023-10-31 15:25 UTC, stejskalleos commented
Closing the PR, it's been two years since the last response.

2023-10-31 15:25 UTC, closed without merging