Fixes #24367 - add support for passphrased keys
theforeman/smart_proxy_ansible pull request #35
Opened 2021-06-07 10:36 UTC by ares

SSH keys protected by the passphrase is not possible to use with pure
Ansible. However ansible-runner provides a way to specify the password
through env/passwords file. For that, the ssh key also needs to be
placed under env/ssh_key (symlink is enough). We already have a
passphrase field in REX Job invocation object, but until now we ignored
that in Ansible jobs.

This patch starts respecting the passphrase for Ansible jobs too. First
it parses the passphrase from the action input. During the
ansible-runner directory preparation, it also creates the env directory.
It symlinks the foreman-proxy key in there and if a passphrase was
specified for the Job invocation, it saves it into the env/passwords
file.

The ansible-runner limitation of a single key means, we can not support
multiple keys with multiple passphrases stored as Host Parameters. The
feature supports only the passphrase specified on the job level, the
same applies to the SSH key. The ansible-runner secrets is only used, if
the passphrase is specified for the job.

Ansible-runner has a bug that we can't easily specify the env/passwords
entry for the ssh-key. The regular expression is only matched with last
100 characters of the line. We can use '^Enter' in the regexp for that
reason. Also the prompt typically contain the full path to the private
key, which is always dynamic. Therefore the regular expression only
contains words artifacts and ssh_key_data: See
https://github.com/ansible/ansible-runner/issues/533 for more details.
The functionality is documented at

* https://ansible-runner.readthedocs.io/en/stable/intro.html#env-ssh-key
* https://ansible-runner.readthedocs.io/en/stable/intro.html#env-passwords

2021-06-08 11:55 UTC, ezr-ondrej commented on lib/smart_proxy_ansible/runner/ansible_runner.rb
> +        secrets = YAML.dump({ "for.*/artifacts/.*/ssh_key_data:" => @passphrase })
Ugh, I've got no idea what are we doing here.

2021-06-17 13:12 UTC, ares commented
Rebased (for the last time I hope) and comment added

2021-06-21 11:16 UTC, adamruzicka requested changes
One more thing to change, apart from it it works nicely

2021-06-21 11:16 UTC, adamruzicka commented on lib/smart_proxy_ansible/runner/ansible_runner.rb
> +        File.symlink(ForemanRemoteExecutionCore.settings[:ssh_identity_key_file], key_path)
The path needs to be expanded first

```
ls -la /home/aruzicka/.foreman-ansible/d20210621-21220-1ml8nlz/env/ssh_key                                                                                                                                                                          
lrwxrwxrwx. 1 aruzicka aruzicka 27 Jun 21 13:12 /home/aruzicka/.foreman-ansible/d20210621-21220-1ml8nlz/env/ssh_key -> '~/.ssh/id_rsa_foreman_proxy'
```

2021-06-24 10:59 UTC, ares commented
udpated

2021-06-24 11:07 UTC, adamruzicka requested changes

2021-06-24 11:07 UTC, adamruzicka commented on lib/smart_proxy_ansible/runner/ansible_runner.rb
> +        File.symlink(ForemanRemoteExecutionCore.settings[:ssh_identity_key_file], key_path)
I should have been more explicit. The path the comes from the settings needs to be expanded

2021-06-25 10:34 UTC, ares commented
updated

2021-07-07 08:34 UTC, adamruzicka approved these changes
ACK

2021-07-07 08:34 UTC, merged

2021-07-07 08:34 UTC, adamruzicka commented
Thank you @ares!